### ISSUE TITLE
incompatibility with Maven 3.3.3

### ISSUE THREAD

**Issue by weberjn** [kevinbirch/string-template-maven-plugin#10]
[ERROR] Failed to execute goal com.webguys:string-template-maven-plugin:1.1:render (default) on project STT: Execution default of goal com.webguys:string-template-maven-plugin:1.1:render failed: An API incompatibility was encountered while executing com.webguys:string-template-maven-plugin:1.1:render: java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;

**Comment by weberjn** [comment]
cloned the sources, rebuild with Maven 3.3.3, the resulting string-template-maven-plugin-1.2-SNAPSHOT.jar works
